### PR TITLE
Fix saving PDFs

### LINKED ISSUE #959: [BUG] Download finished chat is not working for End User
**Bug description:** After chat has finished and when clicking download chat (Lae vestlus alla), nothing happens.

**Expected behavior:** After chat has finished and when clicking download chat (Lae vestlus alla), I should get a new windows to choose where to save the chat and then chat should be downloaded to my device. Was working before

**Screenshots:**

**Additional information:**

### PR DESCRIPTION
**Pull request by IgorKrupenja**
Related task:

- https://github.com/buerokratt/Buerokratt-Chatbot/issues/959

This PR:

- Replaces `html-to-pdf` dependency with using Puppeteer directly which should help.
- Gets rid of unnecessary JSDOM third-party dependency.
- Simplifies the weird and confusing event translation logic understanding which was slowing me down.
- Temporarily adds some debug logging in case this issues needs to be investigated further.

### CODE REVIEW

File: js/generate/convertHtmlToPdf.js [hunk 1]
```diff
@@ -0,0 +1,24 @@
...
+    format: "A4",
+    printBackground: true,
+    timeout: 0,
+  });
+  const base64 = Buffer.from(uintArray).toString("base64");
+  
+  await browser.close();
+
+  const t1 = performance.now();
+  console.log(`convertHtmlToPdf: generated in ${t1 - t0} milliseconds`);
```
Comment (1AhmedYasser) [inline js/generate/convertHtmlToPdf.js]: @IgorKrupenja is this log necessary ?

**Review by 1AhmedYasser — CHANGES_REQUESTED** [review]

File: js/generate/convertHtmlToPdf.js (hunk 1 above)
Comment (IgorKrupenja) [reply js/generate/convertHtmlToPdf.js]: Yeah, removed for now. We can add this debug logging later in case there are still issues with PDF generation.

**Review by 1AhmedYasser — APPROVED** [review]
LGTM
